name: KubeCityBot
version: @version@
main: city.kube.bot.KubeCityBotPlugin
author: Lee0701
authors: [Lee0701]
softdepend: [LuckPerms, RatTranslate]
description: Plugin for KubeCity.
commands:
  kubecitybot:
    aliases: [kubebot, kcb, kb]
    description: "KubeCityBot main command."
  discord:
    description: "Discord link command."
